Added support for optional opacity setting for model in footprint.
mvnmgrx/kiutils pull request #98
Opened 2023-07-28 09:17 UTC by hlprasu

Footprint's model section optionally can have opacity specified in it. This patch adds support to it.

2023-07-30 06:15 UTC, hlprasu commented
@mvnmgrx Kindly review and merge if acceptable.

2023-08-13 02:51 UTC, hlprasu commented
@mvnmgrx Kindly review this.

2023-08-15 18:44 UTC, mvnmgrx requested changes
Thanks for your contribution. I've marked some minor things after which i am happy to merge your PR.

Best regards,

2023-08-16 00:49 UTC, hlprasu commented on src/kiutils/footprint.py
> +    opacity: float = 1.0
Updated.

2023-08-16 00:49 UTC, hlprasu commented on src/kiutils/footprint.py
> +        if self.opacity < 0.999:
Updated.

2023-08-16 00:49 UTC, hlprasu commented on src/kiutils/footprint.py
> +    """Opacity of the element. By default it is set to unity for backward compatibility"""
Updated.

2023-08-16 00:51 UTC, hlprasu commented
> Thanks for your contribution. I've marked some minor things after which i am happy to merge your PR.
> 
> Best regards,

Thanks for the feedback. I've updated as suggested. Kindly review the same.

2023-08-17 19:01 UTC, merged